#ifndef _ERROR_CODES_
#define _ERROR_CODES_

typedef enum {
  ALL_GOOD,

  INITIALIZING_SERVER_FAILED,
  SERVER_CREATION_FAILED,

  INITIALIZING_CLIENT_FAILED,
  CLIENT_CREATION_FAILED,
  CLIENT_CREATING_CONNECTION_FAILED,
} Error_Code;

#endif //_ERROR_CODES_
